attempt to address `TypeError: makedirs() got an unexpected keyword argument 'exists_ok'`, which is highlighted in `159-4-2026-02-17-19-42-45.png` and `159-4-2026-02-17-19-43-32.png`